// scripts/testManifest.mjs — every entry `npm test` runs. The runner is scripts/testRunner.mjs.
//
// Generated 2026-09-14 18:52 EDT from the 132-command `&&` chain it replaced (package.json at 8c5e8a90), in the same order, and hand-maintained from then on. scripts/testRunner.test.mjs fails if a command that chain ran is missing here, and if any *.test.* file in the tree is reached by no entry.
//
// FIELDS
//   cmd        the shell command, run from the repo root
//   lane       unit · docs · hooks · browser. CI runs `browser` as its own job (tests that start Chrome must not share 4 vCPUs with the rest) and every other lane together
//   weight     slots it occupies in the pool. Entries that parallelise internally say so: `check` and the hooks suite use xargs -P, the docs-audit self-test runs 8 shards, each browser walk runs up to 4 pages
//   timeoutMs  per-entry limit; the runner kills the entry's whole process group when it passes (default 300 s)
//   declared   inputs for an entry the node tracer cannot fully see — anything that runs bash, find or xargs. Paths (directories recursive) or { gitFiles: '<pathspec>' }. A shell-shaped entry WITHOUT this is never cached
//   cache      false to never cache an entry locally
//   lock       'tree:write' for an entry that writes source-shaped files into the working tree while it runs, 'tree:read' for one that scans every file on disk. A writer never overlaps a reader; readers share. The runner's store records what each entry wrote, which is how these four were found
//
// ⚠️ ADDING A TEST: add its line here. Adding it to package.json does nothing — `npm test` is the runner now.
export const TESTS = [
    {"cmd": "npm run check", "lane": "unit", "weight": 4, "declared": [{"gitFiles": "*.js"}], "lock": "tree:read"},
    {"cmd": "npm run tdz", "lane": "unit"},
    {"cmd": "node scripts/testCache.test.mjs", "lane": "unit"},
    {"cmd": "node scripts/devlog-add.test.mjs", "lane": "docs"},
    {"cmd": "node scripts/changeStore.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalComposeClient.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalStatus.test.mjs", "lane": "unit"},
    {"cmd": "node scripts/seasonPatchNoteGuard.test.js", "lane": "unit"},
    {"cmd": "npm run docs:audit:test", "lane": "docs", "weight": 4},
    {"cmd": "node scripts/calendarDedup.test.js", "lane": "unit"},
    {"cmd": "node scripts/alertExplain.test.js", "lane": "unit"},
    {"cmd": "node scripts/gatewayRecovery.test.js", "lane": "unit"},
    {"cmd": "node scripts/logger.test.js", "lane": "unit"},
    {"cmd": "node scripts/requestContext.test.js", "lane": "unit"},
    {"cmd": "node scripts/eventStore.test.js", "lane": "unit"},
    {"cmd": "node scripts/rollupStore.test.js", "lane": "unit"},
    {"cmd": "node scripts/cloudObservability.test.js", "lane": "unit"},
    {"cmd": "node scripts/analytics.test.mjs", "lane": "unit"},
    {"cmd": "node scripts/guildPolicy.test.js", "lane": "unit"},
    {"cmd": "node scripts/guildPolicyEnforcement.test.js", "lane": "unit"},
    {"cmd": "node scripts/passiveExpiry.test.js", "lane": "unit"},
    {"cmd": "node scripts/paletteAlgoVersion.test.js", "lane": "unit"},
    {"cmd": "node scripts/paletteShape.test.js", "lane": "unit"},
    {"cmd": "node scripts/animatedMediaPipeline.test.js", "lane": "unit"},
    {"cmd": "node scripts/accentCache.test.js", "lane": "unit"},
    {"cmd": "node scripts/refreshNotice.test.js", "lane": "unit"},
    {"cmd": "node scripts/colorPanelBudget.test.js", "lane": "unit"},
    {"cmd": "node scripts/dynamicPool.test.js", "lane": "unit"},
    {"cmd": "node scripts/colorPaletteCrossViewFetch.test.js", "lane": "unit"},
    {"cmd": "node scripts/handlerRouting.test.js", "lane": "unit"},
    {"cmd": "node scripts/handlerState.test.js", "lane": "unit"},
    {"cmd": "node scripts/hotpatch.test.js", "lane": "unit", "lock": "tree:write"},
    {"cmd": "node scripts/manageActions.test.js", "lane": "unit"},
    {"cmd": "node scripts/botAnalyticsBody.test.js", "lane": "unit"},
    {"cmd": "node scripts/botAccessPermissions.test.js", "lane": "unit"},
    {"cmd": "node scripts/ownerModule.test.js", "lane": "unit"},
    {"cmd": "node scripts/changeInverse.test.js", "lane": "unit"},
    {"cmd": "node scripts/positionalWrite.test.js", "lane": "unit"},
    {"cmd": "node scripts/drawOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/coreOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/changeset.test.js", "lane": "unit"},
    {"cmd": "node scripts/drawsHandlerSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/revert.test.js", "lane": "unit"},
    {"cmd": "node scripts/documentWrite.test.js", "lane": "unit"},
    {"cmd": "node scripts/calendarOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/calendarHandlerSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/loadoutOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/loadoutBulkFormat.test.js", "lane": "unit"},
    {"cmd": "node scripts/loadoutsHandlerSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/patchnoteOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/patchnotesHandlerSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/seasonCountdown.test.js", "lane": "unit"},
    {"cmd": "node scripts/seasonOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/composerForm.test.js", "lane": "unit"},
    {"cmd": "node scripts/analyticsHealth.test.js", "lane": "unit"},
    {"cmd": "node scripts/homeDaysLeft.test.js", "lane": "unit"},
    {"cmd": "node scripts/armoryRealm.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalSession.test.js", "lane": "unit"},
    {"cmd": "node scripts/seasonHandlerSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/announcementOps.test.js", "lane": "unit"},
    {"cmd": "node scripts/announcementDelivery.test.js", "lane": "unit"},
    {"cmd": "node scripts/announcementsHandlerSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/undoRetired.test.js", "lane": "unit"},
    {"cmd": "node scripts/cpPackages.test.js", "lane": "unit"},
    {"cmd": "node scripts/pickerUI.test.js", "lane": "unit"},
    {"cmd": "node scripts/settingsPickers.test.js", "lane": "unit"},
    {"cmd": "node scripts/helpBodySnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/drawCost.test.js", "lane": "unit"},
    {"cmd": "node scripts/drawCalcBudget.test.js", "lane": "unit"},
    {"cmd": "node scripts/catalogGrouping.test.js", "lane": "unit"},
    {"cmd": "node scripts/collectibleCacheKey.test.js", "lane": "unit"},
    {"cmd": "node scripts/syncCatalogToMongo.test.js", "lane": "unit"},
    {"cmd": "node scripts/bulkCacheCollectibles.test.js", "lane": "unit"},
    {"cmd": "node utils/discordCdnAssetIndex.test.js", "lane": "unit"},
    {"cmd": "node scripts/loadoutScopes.test.js", "lane": "unit"},
    {"cmd": "node scripts/loadoutRenderSnapshot.test.js", "lane": "unit"},
    {"cmd": "node scripts/gunsmithsCommandShape.test.js", "lane": "unit"},
    {"cmd": "node scripts/commandCatalog.test.js", "lane": "unit"},
    {"cmd": "node scripts/weaponIndex.test.js", "lane": "unit"},
    {"cmd": "node scripts/instanceLock.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalBuildGates.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalBoot.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalAuth.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalApi.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalPayloadShape.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalUi.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalAsync.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalOneWay.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalOpsReach.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalArmoryBulk.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalPatchNotes.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalExport.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalTips.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalAnalytics.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalRender.test.js", "lane": "unit", "lock": "tree:write"},
    {"cmd": "node scripts/portalPinOverlay.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalContrastRendered.test.js", "lane": "browser", "weight": 1, "timeoutMs": 300000},
    {"cmd": "node scripts/portalRealms.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalReview.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalOpWords.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalRevertId.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalChrome.test.js", "lane": "unit"},
    {"cmd": "npm run portal:orphans", "lane": "unit"},
    {"cmd": "node scripts/portalReverseOrphans.mjs --ci", "lane": "unit"},
    {"cmd": "npm run portal:reverse-orphans:test", "lane": "unit"},
    {"cmd": "npm run portal:template-comments", "lane": "unit"},
    {"cmd": "npm run portal:template-comments:test", "lane": "unit"},
    {"cmd": "npm run portal:stylerank:test", "lane": "unit"},
    {"cmd": "npm run portal:realwalk:test", "lane": "unit"},
    {"cmd": "npm run portal:geometry:test", "lane": "unit"},
    {"cmd": "npm run portal:states:test", "lane": "unit"},
    {"cmd": "node scripts/portalStates.mjs --ci", "lane": "browser", "weight": 4, "timeoutMs": 600000},
    {"cmd": "node scripts/portalGeometry.mjs --all --check", "lane": "browser", "weight": 4, "timeoutMs": 300000},
    {"cmd": "node scripts/portalHarness.test.js", "lane": "unit"},
    {"cmd": "node scripts/portalHarnessRender.test.js", "lane": "unit", "lock": "tree:write"},
    {"cmd": "node scripts/portalRoutes.test.js", "lane": "unit"},
    {"cmd": "node scripts/handoffCheck.test.mjs", "lane": "docs"},
    {"cmd": "node scripts/agreementSize.test.mjs", "lane": "docs"},
    {"cmd": "node scripts/silentContract.test.mjs", "lane": "docs"},
    {"cmd": "npm run docs:reflow:test", "lane": "docs"},
    {"cmd": "npm run docs:reflow", "lane": "docs"},
    {"cmd": "npm run docs:reflow-comments:test", "lane": "docs"},
    {"cmd": "npm run docs:reflow-comments", "lane": "docs"},
    {"cmd": "npm run portal:gate", "lane": "unit"},
    {"cmd": "npm run portal:refs", "lane": "unit"},
    {"cmd": "npm run portal:uxcopy", "lane": "unit"},
    {"cmd": "npm run portal:roundtrip", "lane": "unit"},
    {"cmd": "npm run portal:coverage:test", "lane": "unit"},
    {"cmd": "npm run test:tz", "lane": "unit"},
    {"cmd": "npm run autofix:safety", "lane": "unit"},
    {"cmd": "npm run test:hooks", "lane": "hooks", "weight": 4, "declared": [".claude/hooks", "scripts/hookOutputCap.test.sh", "scripts/testCache.mjs", ".claude/settings.json"]},
    {"cmd": "node --no-warnings scripts/indexHealth.test.mjs", "lane": "unit"},
    {"cmd": "node scripts/hookTestLint.test.mjs", "lane": "unit"},
    {"cmd": "node scripts/buildPortalInputs.test.mjs", "lane": "unit"},
    {"cmd": "node scripts/testRunner.test.mjs", "lane": "unit"},
];
